name: Default Codeplugs

on:
  push:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Build Codeplugs
      env:
        REPEATERBOOK_USER: ${{ secrets.REPEATERBOOK_USER }}
        REPEATERBOOK_PASSWD: ${{ secrets.REPEATERBOOK_PASSWD }}
      run: |
        find ./codeplug -name 'generate.sh' -exec /bin/bash {} \;
    - name: Archive Codeplugs
      uses: actions/upload-artifact@v2
      with:
        name: default-codeplug
        path: OUTPUT
    - name: Get release
      id: get_release
      if: ${{ github.event_name == 'release' }}
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create release ZIP
      if: ${{ github.event_name == 'release' }}
      run: |
        zip -r default-codeplug.zip OUTPUT/*
    - name: Upload artifact to release
      id: upload-release-asset 
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_path: ./default-codeplug.zip
        asset_name: default-codeplug.zip
        asset_content_type: application/zip
